### ISSUE TITLE
Back to root

### ISSUE THREAD

**Issue by dzyasseron** [Senky/phpbb-ext-ajax-base#2]
Nice addon, but it refreshes the page and if forum is installed in a subfolder, it breaks the statistics.
Got the mod "Extended Statistics on Index", and after the Ajax refresh, the newest user link doesn't go to %url/folder but just to %url

**Comment by rxu** [comment]
Possible fix: https://github.com/Tatiana5/phpbb-ext-ajax-base/commit/61eeb43d20a4455b4ece3e757730f90584aee3f4

**Comment by senky** [comment]
Fixed in https://github.com/senky/phpbb-ext-ajax-base/commit/39577618106e42acc6e9d9358f2b105992495fd7. Thanks to [Tatiana5](https://github.com/Tatiana5)!
